// Generated by CoffeeScript 1.4.0
(function() {
  var root;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.Routes = (function() {

    function Routes() {}

    Routes.prototype.index = function(req, res) {
      return res.render('index');
    };

    Routes.prototype.test = function(req, res) {
      return res.render('test');
    };

    Routes.prototype.versus = function(req, res) {
      return res.render('versus');
    };

    Routes.prototype.form = function(req, res) {
      return res.render('form');
    };

    return Routes;

  })();

}).call(this);
